In [3]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.18.1'

In [4]:
pd.__version__

'1.0.1'

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Create a matrix with a predined value
np.full((3,5),fill_value=1.5,dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
int(1.5)

1

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Array indexing

In [13]:
x1 = np.array([4,3,4,4,8,4])
x1

array([4, 3, 4, 4, 8, 4])

In [14]:
# access the value to index zero

In [15]:
x1[0]

4

In [16]:
x1[4]

8

In [17]:
x1[-1]

4

In [18]:
# In a multidimmensional array, we need to specify row and column index

In [19]:
x2 = np.array([[3,7,5,5],[0,1,5,9],[3,0,5,0]])
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [20]:
# 3rd row and lastvalue from the 3rd column

In [30]:
x2[2,-1]

0

In [21]:
l = [[1,2],[2,6]]

In [31]:
l[1][1] = 7

In [25]:
a = 'venkat',

In [26]:
type(a)

tuple

In [32]:
l

[[1, 2], [2, 7]]

In [33]:
x2[0,0] = 12

In [34]:
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [35]:
x = np.arange(20)

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
x[:5]

array([0, 1, 2, 3, 4])

In [38]:
x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
x[4:7]

array([4, 5, 6])

In [42]:
x[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [43]:
x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [44]:
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [45]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [47]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[4,5,6]])
np.vstack([x,grid])

array([[3, 4, 5],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
z = np.array([[9],[9]])

In [64]:
z

array([[9],
       [9]])

In [65]:
np.hstack([z,grid])

array([[9, 1, 2, 3],
       [9, 4, 5, 6]])

In [66]:
x = np.arange(10)

In [67]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
x1,x2,x3 = np.split(x,[3,5])

In [84]:
x1

array([0, 1, 2])

In [85]:
x2

array([3, 4])

In [86]:
x3

array([5, 6, 7, 8, 9])

In [87]:
x1,x2,x3 = np.split(x,[3,4])

In [88]:
x1

array([0, 1, 2])

In [89]:
x2

array([3])

In [90]:
x3

array([4, 5, 6, 7, 8, 9])

In [91]:
grid = np.arange(16)

In [92]:
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
grid = np.arange(16).reshape((4,4))

In [94]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
grid = np.arange(16).reshape((7,3))

ValueError: cannot reshape array of size 16 into shape (7,3)

In [96]:
grid = np.arange(16).reshape((8,2))

In [97]:
grid

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [98]:
grid = np.arange(16).reshape((2,8))

In [99]:
grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [100]:
def shape(n,x1,x2):
    grid = np.arange(n).reshape((x1,x2))
    return grid

In [101]:
shape(16,8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [103]:
shape(16,4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
data = pd.DataFrame({'group':['x','x','x','y','y','y','z','z','z'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [105]:
data

group  ounces
0     x     4.0
1     x     3.0
2     x    12.0
3     y     6.0
4     y     7.5
5     y     8.0
6     z     3.0
7     z     5.0
8     z     6.0

In [106]:
data['ounces'].sort_values()

1     3.0
6     3.0
0     4.0
7     5.0
3     6.0
8     6.0
4     7.5
5     8.0
2    12.0
Name: ounces, dtype: float64

In [108]:
data.sort_values(by=['ounces'],ascending=False).reset_index(drop=True)

group  ounces
0     x    12.0
1     y     8.0
2     y     7.5
3     y     6.0
4     z     6.0
5     z     5.0
6     x     4.0
7     x     3.0
8     z     3.0

In [109]:
data.sort_values(by=['group','ounces'],ascending=False).reset_index(drop=True)

group  ounces
0     z     6.0
1     z     5.0
2     z     3.0
3     y     8.0
4     y     7.5
5     y     6.0
6     x    12.0
7     x     4.0
8     x     3.0

In [110]:
data = pd.DataFrame({'k1':['one']*3+['two']*4,'k2':[3,2,1,3,3,4,4]})

In [111]:
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [112]:
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [113]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

In [117]:
data.drop_duplicates(subset='k2')

k1  k2
0  one   3
1  one   2
2  one   1
5  two   4

In [124]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami'],'ounces':[4,3,12,6]})

In [125]:
data

food  ounces
0        bacon       4
1  pulled pork       3
2        bacon      12
3     Pastrami       6

In [139]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow'
}

In [140]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [141]:
data

food  ounces animal
0        bacon       4    pig
1  pulled pork       3    pig
2        bacon      12    pig
3     Pastrami       6    cow

In [142]:
data['ounces_14'] = data['ounces']*14

In [143]:
data

food  ounces animal  ounces_14
0        bacon       4    pig         56
1  pulled pork       3    pig         42
2        bacon      12    pig        168
3     Pastrami       6    cow         84

In [146]:
data = data.assign(new_col=data['ounces']*14)

In [147]:
data

food  ounces animal  ounces_14  new_col
0        bacon       4    pig         56       56
1  pulled pork       3    pig         42       42
2        bacon      12    pig        168      168
3     Pastrami       6    cow         84       84

In [148]:
data.drop('new_col',axis='columns',inplace=True)

In [149]:
data

food  ounces animal  ounces_14
0        bacon       4    pig         56
1  pulled pork       3    pig         42
2        bacon      12    pig        168
3     Pastrami       6    cow         84

In [151]:
data = pd.DataFrame(np.arange(12).reshape(3,4),index=['ohio','colorado','New York'],
                   columns=['one','two','three','four'])

In [152]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
New York    8    9     10    11

In [153]:
data.rename(index={'ohio':'sanf'},columns={'one':'one_p','two':'two_p'},inplace=True)

In [154]:
data

one_p  two_p  three  four
sanf          0      1      2     3
colorado      4      5      6     7
New York      8      9     10    11

In [155]:
data.rename(index=str.upper,columns=str.title,inplace=True)

In [156]:
data

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

In [157]:
data.rename(index=str.upper,columns=str.upper,inplace=True)

In [158]:
data

ONE_P  TWO_P  THREE  FOUR
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11